import { KnownChar } from './KnownChar';
import { KnownCharId } from './KnownCharId';
import * as intents from './intents'

export const knownChars: KnownChar[] = [
    {
        id: KnownCharId.Wolf,
        title: '🐺 Серого волка',
        normal: 'волк',
        trigger: intents.wolf,
        image: '965417/9929614145838c2092ab',
    },
    {
        id: KnownCharId.Crow,
        title: '🐦 Ворону',
        normal: 'ворона',
        trigger: intents.crow,
        image: '997614/61c6fab9d5da7f3a5eba',
    },
    {
        id: KnownCharId.Cat,
        title: '🐱 Маленького котёнка',
        normal: 'котёнк',
        trigger: intents.cat,
        image: '1540737/52f138d32164dcfb334b',
    },
    {
        id: KnownCharId.Mouse,
        title: '🐭 Мышку',
        normal: 'мышка',
        trigger: intents.mouse,
        image: '1652229/dec46e3a051abd7eef90',
    },
    {
        id: KnownCharId.Dog,
        title: '🐶 Собаку',
        normal: 'собака',
        trigger: intents.dog,
        image: '1030494/fb311cc1fb2cb7fafa8a',
    },
    {
        id: KnownCharId.Granny,
        title: '👵 Бабушку',
        normal: 'бабушка',
        trigger: intents.granny,
        image: '965417/3f0555dd5901a0823e39',
    },
    {
        id: KnownCharId.Lion,
        title: '🦁 Большого льва',
        normal: 'лев',
        trigger: intents.lion,
        image: '965417/e6c5fce891628ea6db10',
    },
    {
        id: KnownCharId.Elephant,
        title: '🐘 Слона',
        normal: 'слон',
        trigger: intents.elephant,
        image: '1540737/8d397cb056499591db59',
    },
    {
        id: KnownCharId.Rooster,
        title: '🐓 Петушка',
        normal: 'петушок',
        trigger: intents.rooster,
        image: '965417/d12602b30f51439b55b3',
    },
    {
        id: KnownCharId.Owl,
        title: '🦉Сову',
        normal: 'сова',
        trigger: intents.owl,
        image: '1030494/246c82db66034ba90a3f',
    },
    {
        id: KnownCharId.Chicken,
        title: '🐔 Курочку',
        normal: 'курочка',
        trigger: intents.chicken,
        image: '213044/bb381ed46a4a6ed4cf2b',
    },
    {
        id: KnownCharId.Bear,
        title: '🐻 Бурого мишку',
        normal: 'мишка',
        trigger: intents.bear,
        image: '1656841/1683fc7e7260af4218c4',
    },
    {
        id: KnownCharId.Fox,
        title: '🦊 Лисичку',
        normal: 'лисичка',
        trigger: intents.fox,
        image: '965417/a07c3f1a434e63760055',
    },
    {
        id: KnownCharId.Fish,
        title: '🐠 Золотую рыбку',
        normal: 'рыбка',
        trigger: intents.fish,
        image: '',
    },
    {
        id: KnownCharId.Girl,
        title: '👧 Внучку',
        normal: 'внучка',
        trigger: intents.girl,
        image: '965417/04042969d5ad6db34bc3',
    },
    {
        id: KnownCharId.Zombie,
        title: '🧟‍ Зомби',
        normal: 'зомби',
        trigger: intents.zombie,
        image: '',
    },
    {
        id: KnownCharId.Grandfather,
        title: '👴 Дедушку',
        normal: 'дедушка',
        trigger: intents.grandfather,
        image: '',
    },
    {
        id: KnownCharId.Alice,
        title: '📱 Алису',
        normal: 'алиса',
        trigger: intents.alice,
        image: '1030494/941a763ac0fcc18e2be8',
    },
    {
        id: KnownCharId.HarryPotter,
        title: '🧙‍♂️ Гарри Поттера',
        normal: 'гарри поттер',
        trigger: intents.harryPotter,
        image: '',
    },
    {
        id: KnownCharId.Rat,
        title: '🐁 Крысу',
        normal: 'крыса',
        trigger: intents.rat,
        image: '',
    },
    {
        id: KnownCharId.Cow,
        title: '🐮 Коровушку',
        normal: 'коровушка',
        trigger: intents.cow,
        image: '',
    },
    {
        id: KnownCharId.Crocodile,
        title: '🐊 Крокодила',
        normal: 'крокодил',
        trigger: intents.crocodile,
        image: '',
    },
    {
        id: KnownCharId.Tiger,
        title: '🐯 Тигра',
        normal: 'тигр',
        trigger: intents.tiger,
        image: '',
    },
    {
        id: KnownCharId.Dino,
        title: '🦖 Динозавра',
        normal: 'динозавр',
        trigger: intents.dino,
        image: '',
    },
];
